RW_FUNDINFO_MAPPING = {
    "forgcode" : '표준코드',
    "fmngcomcd" : '운용회사',
    "fundnm" : '펀드명',
    "setupymd" : '설정일',
    "fundtype" : '펀드유형',
    "investpl" : '투자지역',
    "acctcomp" : '수탁회사',
    "salecomp" : '대표판매사',
    "vfundgbnm" : '구분',
    "ufundtypnm" : '상품분류',
    "vadditionalestmtdnm" : '추가/단위구분',
    "establishmentdt" : '최초설정일',
    "classcd" : '분류코드',
    "shortcd" : '단축코드',
    "trustacctrm" : '신탁회계기간',
    "vinvestrgngbnm" : '투자지역구분',
    "vsalergngbnm" : '판매지역구분',
    "vprofittypecdnm" : '운용실적공시분류',
    "vtraitdivnm" : '특성분류',
    "vpripubgbnm" : '공시/사모구분',
    "establishmentcot" : '최소설정기준가격',
    "trusttrm" : '신탁기간',
    "managerewrate" : '운용보수',
    "salerewrate" : '판매보수',
    "trustrewrate" : '수탁보수',
    "generalofctrtrewrate" : '일반사무수탁보수',
    "rewsum" : '보수합계',
    "ter" : '총비율이율(TER)',
    "frontendcmsrate" : '선취수수료',
    "backendcmsrate" : '후취수수료',
    "vmanagecompnm" : '운용회사',
    "vgeneralofctrtcompnm" : '일반사무수탁회사',
    "vtrustcompnm" : '수탁회사상세',
    "companycd" : '회사코드',
    "uoriginalamt" : '설정원본',
    "netasstotamt" : '순자산총액',
}

RW_FUNDINDEX = {
    '표준코드'       		:      	'forgcode'			,
	'기준일자'       		:      	'standarddt'		,
    '기준가격'       		:      	'standardcot'		,
    '전일대비등락'      	:       'vbefdayfltstdcot'	,
    '과표기준가격'      	:       'standardassstdcot'	,
    '설정원본'       	    :     	'uoriginalamt'     	,
    'KOSPI'       		:      	'kospiepn'			,
    'KOSPI200'      	:       'kospi200epn'		,
    'KOSDAQ'       		:      	'kosdaqepn'			,
    '국공채(3년만기)'   	:       'tbondbnd3y'		,
    '회사채(3년만기)'       :       'companybnd3y'      ,
}

RW_FUNDSETTLE = {
    '표준코드'			: 'forgcode'			,  
    '신탁회계기초'		: 'trustaccsrt'		    , 
    '신탁회계기말'		: 'trustaccend'		    , 
    '경과일수'			: 'vpassdaycnt'		  	,
    '기준'       		:  'standardcot'		,
    '과표'			:  'standardasscot'		,
    '설정원본'			: 'uoriginalamt'        ,
    '결산'			: 'vsettlegbnm'			,
}
