# Api Default Values
FIRST_INITIAL_DATE = '19900101'
DEFAULT_AGO_DAYS = 7
DATESTR_FMT = "%Y%m%d"

# DB Table names
FUNDINFO_TABLE_NAME = 'RW_FUNDINFO'
FUNDSETTLE_EXSO_TABLE_NAME = 'RW_FUNDSETTLE'
RW_FUNDINDEX_TABLE_NAME = 'RW_FUNDINDEX'
